// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: NFDefine.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NFMsg {

  /// <summary>Holder for reflection information generated from NFDefine.proto</summary>
  public static partial class NFDefineReflection {

    #region Descriptor
    /// <summary>File descriptor for NFDefine.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NFDefineReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5ORkRlZmluZS5wcm90bxIFTkZNc2cqswMKDkVHYW1lRXZlbnRDb2RlEgsK",
            "B1NVQ0NFU1MQABIQCgxVTktPV05fRVJST1IQARIRCg1BQ0NPVU5UX0VYSVNU",
            "EAISFgoSQUNDT1VOVFBXRF9JTlZBTElEEAMSEQoNQUNDT1VOVF9VU0lORxAE",
            "EhIKDkFDQ09VTlRfTE9DS0VEEAUSEwoPQUNDT1VOVF9TVUNDRVNTEAYSFgoS",
            "VkVSSUZZX0tFWV9TVUNDRVNTEAcSEwoPVkVSSUZZX0tFWV9GQUlMEAgSGAoU",
            "U0VMRUNUU0VSVkVSX1NVQ0NFU1MQCRIVChFTRUxFQ1RTRVJWRVJfRkFJTBAK",
            "EhMKD0NIQVJBQ1RFUl9FWElTVBBuEhUKEVNWUlpPTkVJRF9JTlZBTElEEG8S",
            "FAoQQ0hBUkFDVEVSX05VTU9VVBBwEhUKEUNIQVJBQ1RFUl9JTlZBTElEEHES",
            "FgoSQ0hBUkFDVEVSX05PVEVYSVNUEHISEwoPQ0hBUkFDVEVSX1VTSU5HEHMS",
            "FAoQQ0hBUkFDVEVSX0xPQ0tFRBB0EhEKDVpPTkVfT1ZFUkxPQUQQdRIOCgpO",
            "T1RfT05MSU5FEHYqhBIKCkVHYW1lTXNnSUQSCgoGVU5LTk9XEAASEAoMRVZF",
            "TlRfUkVTVUxUEAESEwoPRVZFTlRfVFJBTlNQT1JUEAISEAoMQ0xPU0VfU09D",
            "S0VUEAMSEwoPRVZFTlRfQlVZX0xFVkVMEAQSFgoSRVZFTlRfUkVGUkVTSF9T",
            "SE9QEAUSDgoKRVZFTlRfRVhJVBAGEhMKD0VWRU5UX1JFQ09OTkVDVBAHEhYK",
            "EkVWRU5UX0JVWV9DSEFNUElPThAIEhcKE0VWRU5UX1NFTExfQ0hBTVBJT04Q",
            "CRIYChRXVE1fV09STERfUkVHSVNURVJFRBAKEhoKFldUTV9XT1JMRF9VTlJF",
            "R0lTVEVSRUQQCxIVChFXVE1fV09STERfUkVGUkVTSBAMEhsKF0FDS19FVkVO",
            "VF9TRUxMX0NIQU1QSU9OEA0SGAoUTFRNX0xPR0lOX1JFR0lTVEVSRUQQFBIa",
            "ChZMVE1fTE9HSU5fVU5SRUdJU1RFUkVEEBUSFQoRTFRNX0xPR0lOX1JFRlJF",
            "U0gQFhIZChVQVFdHX1BST1hZX1JFR0lTVEVSRUQQHhIbChdQVFdHX1BST1hZ",
            "X1VOUkVHSVNURVJFRBAfEhYKElBUV0dfUFJPWFlfUkVGUkVTSBAgEhcKE0dU",
            "V19HQU1FX1JFR0lTVEVSRUQQKBIZChVHVFdfR0FNRV9VTlJFR0lTVEVSRUQQ",
            "KRIUChBHVFdfR0FNRV9SRUZSRVNIECoSFQoRRFRXX0RCX1JFR0lTVEVSRUQQ",
            "PBIXChNEVFdfREJfVU5SRUdJU1RFUkVEED0SEgoORFRXX0RCX1JFRlJFU0gQ",
            "PhIQCgxTVFNfTkVUX0lORk8QRhIQCgxSRVFfTEFHX1RFU1QQUBIVChFBQ0tf",
            "R0FURV9MQUdfVEVTVBBREhUKEUFDS19HQU1FX0xBR19URVNUEFISFQoRU1RT",
            "X1NFUlZFUl9SRVBPUlQQWhISCg5TVFNfSEVBUlRfQkVBVBBkEg0KCVJFUV9M",
            "T0dJThBlEg0KCUFDS19MT0dJThBmEg4KClJFUV9MT0dPVVQQZxISCg5SRVFf",
            "V09STERfTElTVBBuEhIKDkFDS19XT1JMRF9MSVNUEG8SFQoRUkVRX0NPTk5F",
            "Q1RfV09STEQQcBIVChFBQ0tfQ09OTkVDVF9XT1JMRBBxEhsKF1JFUV9LSUNL",
            "X0NMSUVOVF9JTldPUkxEEHISEwoPUkVRX0NPTk5FQ1RfS0VZEHgSEwoPQUNL",
            "X0NPTk5FQ1RfS0VZEHoSFgoRUkVRX1NFTEVDVF9TRVJWRVIQggESFgoRQUNL",
            "X1NFTEVDVF9TRVJWRVIQgwESEgoNUkVRX1JPTEVfTElTVBCEARISCg1BQ0tf",
            "Uk9MRV9MSVNUEIUBEhQKD1JFUV9DUkVBVEVfUk9MRRCGARIUCg9SRVFfREVM",
            "RVRFX1JPTEUQhwESFQoQUkVRX1JFQ09WRVJfUk9MRRCIARIXChJSRVFfTE9B",
            "RF9ST0xFX0RBVEEQjAESFwoSQUNLX0xPQURfUk9MRV9EQVRBEI0BEhcKElJF",
            "UV9TQVZFX1JPTEVfREFUQRCOARIXChJBQ0tfU0FWRV9ST0xFX0RBVEEQjwES",
            "EwoOUkVRX0VOVEVSX0dBTUUQlgESEwoOQUNLX0VOVEVSX0dBTUUQlwESEwoO",
            "UkVRX0xFQVZFX0dBTUUQmAESEwoOQUNLX0xFQVZFX0dBTUUQmQESEgoNUkVR",
            "X1NXQVBfR0FNRRCaARITCg5SRVFfU1dBUF9TQ0VORRCbARITCg5BQ0tfU1dB",
            "UF9TQ0VORRCcARIYChNSRVFfU1dBUF9IT01FX1NDRU5FEJ0BEhgKE0FDS19T",
            "V0FQX0hPTUVfU0NFTkUQngESGgoVUkVRX0VOVEVSX0dBTUVfRklOSVNIEJ8B",
            "EhoKFUFDS19FTlRFUl9HQU1FX0ZJTklTSBCgARIVChBBQ0tfT0JKRUNUX0VO",
            "VFJZEMgBEhUKEEFDS19PQkpFQ1RfTEVBVkUQyQESHgoZQUNLX09CSkVDVF9Q",
            "Uk9QRVJUWV9FTlRSWRDKARIcChdBQ0tfT0JKRUNUX1JFQ09SRF9FTlRSWRDL",
            "ARIVChBBQ0tfUFJPUEVSVFlfSU5UENIBEhcKEkFDS19QUk9QRVJUWV9GTE9B",
            "VBDTARIYChNBQ0tfUFJPUEVSVFlfU1RSSU5HENQBEhgKE0FDS19QUk9QRVJU",
            "WV9PQkpFQ1QQ1gESGQoUQUNLX1BST1BFUlRZX1ZFQ1RPUjIQ1wESGQoUQUNL",
            "X1BST1BFUlRZX1ZFQ1RPUjMQ2AESFwoSQUNLX1BST1BFUlRZX0NMRUFSENkB",
            "EhAKC0FDS19BRERfUk9XENwBEhMKDkFDS19SRU1PVkVfUk9XEN0BEhEKDEFD",
            "S19TV0FQX1JPVxDeARITCg5BQ0tfUkVDT1JEX0lOVBDfARIVChBBQ0tfUkVD",
            "T1JEX0ZMT0FUEOABEhYKEUFDS19SRUNPUkRfU1RSSU5HEOIBEhYKEUFDS19S",
            "RUNPUkRfT0JKRUNUEOMBEhcKEkFDS19SRUNPUkRfVkVDVE9SMhDkARIXChJB",
            "Q0tfUkVDT1JEX1ZFQ1RPUjMQ5QESFQoQQUNLX1JFQ09SRF9DTEVBUhD6ARIU",
            "Cg9BQ0tfUkVDT1JEX1NPUlQQ+wESFgoRQUNLX0RBVEFfRklOSVNIRUQQhAIS",
            "EQoMUkVRX0FJX09OV0VSEI4CEg0KCFJFUV9NT1ZFEKwCEg0KCEFDS19NT1ZF",
            "EK0CEhQKD1JFUV9NT1ZFX0lNTVVORRCuAhIUCg9BQ0tfTU9WRV9JTU1VTkUQ",
            "rwISEQoMUkVRX1BPU19TWU5DELICEhEKDEFDS19QT1NfU1lOQxCzAhINCghS",
            "RVFfQ0hBVBDeAhINCghBQ0tfQ0hBVBDfAhIWChFSRVFfU0tJTExfT0JKRUNU",
            "WBCQAxIWChFBQ0tfU0tJTExfT0JKRUNUWBCRAxISCg1SRVFfU0tJTExfUE9T",
            "EJIDEhIKDUFDS19TS0lMTF9QT1MQkwMSFgoRQUNLX09OTElORV9OT1RJRlkQ",
            "2AQSFwoSQUNLX09GRkxJTkVfTk9USUZZENkEKkcKCUVJdGVtVHlwZRINCglF",
            "SVRfRVFVSVAQABILCgdFSVRfR0VNEAESDgoKRUlUX1NVUFBMWRACEg4KCkVJ",
            "VF9TQ1JPTEwQAyq3AQoKRVNraWxsVHlwZRIWChJCUklFRl9TSU5HTEVfU0tJ",
            "TEwQABIVChFCUklFRl9HUk9VUF9TS0lMTBABEhcKE0JVTExFVF9TSU5HTEVf",
            "U0tJTEwQAhIYChRCVUxMRVRfUkVCT1VORF9TS0lMTBADEhwKGEJVTExFVF9U",
            "QVJHRVRfQk9NQl9TS0lMTBAEEhkKFUJVTExFVF9QT1NfQk9NQl9TS0lMTBAF",
            "Eg4KCkZVTkNfU0tJTEwQBiqOAQoKRVNjZW5lVHlwZRIQCgxOT1JNQUxfU0NF",
            "TkUQABIWChJTSU5HTEVfQ0xPTkVfU0NFTkUQARIVChFNVUxUSV9DTE9ORV9T",
            "Q0VORRACEhIKDlBWUF9NT0RFX1NDRU5FEAoSEgoOTVZNX01PREVfU0NFTkUQ",
            "CxIXChNTVVJWSVZBTF9NT0RFX1NDRU5FEAwqRgoIRU5QQ1R5cGUSDgoKTk9S",
            "TUFMX05QQxAAEgwKCEhFUk9fTlBDEAESDgoKVFVSUkVUX05QQxACEgwKCEZV",
            "TkNfTlBDEANiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::NFMsg.EGameEventCode), typeof(global::NFMsg.EGameMsgID), typeof(global::NFMsg.EItemType), typeof(global::NFMsg.ESkillType), typeof(global::NFMsg.ESceneType), typeof(global::NFMsg.ENPCType), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///events
  /// </summary>
  public enum EGameEventCode {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("SUCCESS")] Success = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("UNKOWN_ERROR")] UnkownError = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACCOUNT_EXIST")] AccountExist = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACCOUNTPWD_INVALID")] AccountpwdInvalid = 3,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACCOUNT_USING")] AccountUsing = 4,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACCOUNT_LOCKED")] AccountLocked = 5,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACCOUNT_SUCCESS")] AccountSuccess = 6,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("VERIFY_KEY_SUCCESS")] VerifyKeySuccess = 7,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("VERIFY_KEY_FAIL")] VerifyKeyFail = 8,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("SELECTSERVER_SUCCESS")] SelectserverSuccess = 9,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("SELECTSERVER_FAIL")] SelectserverFail = 10,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("CHARACTER_EXIST")] CharacterExist = 110,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("SVRZONEID_INVALID")] SvrzoneidInvalid = 111,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("CHARACTER_NUMOUT")] CharacterNumout = 112,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("CHARACTER_INVALID")] CharacterInvalid = 113,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("CHARACTER_NOTEXIST")] CharacterNotexist = 114,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("CHARACTER_USING")] CharacterUsing = 115,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("CHARACTER_LOCKED")] CharacterLocked = 116,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ZONE_OVERLOAD")] ZoneOverload = 117,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("NOT_ONLINE")] NotOnline = 118,
  }

  public enum EGameMsgID {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("UNKNOW")] Unknow = 0,
    /// <summary>
    /// for events
    /// </summary>
    [pbr::OriginalName("EVENT_RESULT")] EventResult = 1,
    /// <summary>
    /// for events
    /// </summary>
    [pbr::OriginalName("EVENT_TRANSPORT")] EventTransport = 2,
    /// <summary>
    /// want to close some one
    /// </summary>
    [pbr::OriginalName("CLOSE_SOCKET")] CloseSocket = 3,
    [pbr::OriginalName("EVENT_BUY_LEVEL")] EventBuyLevel = 4,
    [pbr::OriginalName("EVENT_REFRESH_SHOP")] EventRefreshShop = 5,
    [pbr::OriginalName("EVENT_EXIT")] EventExit = 6,
    [pbr::OriginalName("EVENT_RECONNECT")] EventReconnect = 7,
    [pbr::OriginalName("EVENT_BUY_CHAMPION")] EventBuyChampion = 8,
    [pbr::OriginalName("EVENT_SELL_CHAMPION")] EventSellChampion = 9,
    [pbr::OriginalName("WTM_WORLD_REGISTERED")] WtmWorldRegistered = 10,
    [pbr::OriginalName("WTM_WORLD_UNREGISTERED")] WtmWorldUnregistered = 11,
    [pbr::OriginalName("WTM_WORLD_REFRESH")] WtmWorldRefresh = 12,
    [pbr::OriginalName("ACK_EVENT_SELL_CHAMPION")] AckEventSellChampion = 13,
    [pbr::OriginalName("LTM_LOGIN_REGISTERED")] LtmLoginRegistered = 20,
    [pbr::OriginalName("LTM_LOGIN_UNREGISTERED")] LtmLoginUnregistered = 21,
    [pbr::OriginalName("LTM_LOGIN_REFRESH")] LtmLoginRefresh = 22,
    [pbr::OriginalName("PTWG_PROXY_REGISTERED")] PtwgProxyRegistered = 30,
    [pbr::OriginalName("PTWG_PROXY_UNREGISTERED")] PtwgProxyUnregistered = 31,
    [pbr::OriginalName("PTWG_PROXY_REFRESH")] PtwgProxyRefresh = 32,
    [pbr::OriginalName("GTW_GAME_REGISTERED")] GtwGameRegistered = 40,
    [pbr::OriginalName("GTW_GAME_UNREGISTERED")] GtwGameUnregistered = 41,
    [pbr::OriginalName("GTW_GAME_REFRESH")] GtwGameRefresh = 42,
    [pbr::OriginalName("DTW_DB_REGISTERED")] DtwDbRegistered = 60,
    [pbr::OriginalName("DTW_DB_UNREGISTERED")] DtwDbUnregistered = 61,
    [pbr::OriginalName("DTW_DB_REFRESH")] DtwDbRefresh = 62,
    [pbr::OriginalName("STS_NET_INFO")] StsNetInfo = 70,
    [pbr::OriginalName("REQ_LAG_TEST")] ReqLagTest = 80,
    [pbr::OriginalName("ACK_GATE_LAG_TEST")] AckGateLagTest = 81,
    [pbr::OriginalName("ACK_GAME_LAG_TEST")] AckGameLagTest = 82,
    [pbr::OriginalName("STS_SERVER_REPORT")] StsServerReport = 90,
    [pbr::OriginalName("STS_HEART_BEAT")] StsHeartBeat = 100,
    /// <summary>
    ///////////////////////////////////////////////////////////////////////////////////////
    /// </summary>
    [pbr::OriginalName("REQ_LOGIN")] ReqLogin = 101,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_LOGIN")] AckLogin = 102,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_LOGOUT")] ReqLogout = 103,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_WORLD_LIST")] ReqWorldList = 110,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_WORLD_LIST")] AckWorldList = 111,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_CONNECT_WORLD")] ReqConnectWorld = 112,
    [pbr::OriginalName("ACK_CONNECT_WORLD")] AckConnectWorld = 113,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_KICK_CLIENT_INWORLD")] ReqKickClientInworld = 114,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_CONNECT_KEY")] ReqConnectKey = 120,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_CONNECT_KEY")] AckConnectKey = 122,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_SELECT_SERVER")] ReqSelectServer = 130,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_SELECT_SERVER")] AckSelectServer = 131,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_ROLE_LIST")] ReqRoleList = 132,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_ROLE_LIST")] AckRoleList = 133,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_CREATE_ROLE")] ReqCreateRole = 134,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_DELETE_ROLE")] ReqDeleteRole = 135,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_RECOVER_ROLE")] ReqRecoverRole = 136,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_LOAD_ROLE_DATA")] ReqLoadRoleData = 140,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_LOAD_ROLE_DATA")] AckLoadRoleData = 141,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_SAVE_ROLE_DATA")] ReqSaveRoleData = 142,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_SAVE_ROLE_DATA")] AckSaveRoleData = 143,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_ENTER_GAME")] ReqEnterGame = 150,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_ENTER_GAME")] AckEnterGame = 151,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_LEAVE_GAME")] ReqLeaveGame = 152,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_LEAVE_GAME")] AckLeaveGame = 153,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_SWAP_GAME")] ReqSwapGame = 154,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_SWAP_SCENE")] ReqSwapScene = 155,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_SWAP_SCENE")] AckSwapScene = 156,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_SWAP_HOME_SCENE")] ReqSwapHomeScene = 157,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_SWAP_HOME_SCENE")] AckSwapHomeScene = 158,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_ENTER_GAME_FINISH")] ReqEnterGameFinish = 159,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_ENTER_GAME_FINISH")] AckEnterGameFinish = 160,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_OBJECT_ENTRY")] AckObjectEntry = 200,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_OBJECT_LEAVE")] AckObjectLeave = 201,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_OBJECT_PROPERTY_ENTRY")] AckObjectPropertyEntry = 202,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_OBJECT_RECORD_ENTRY")] AckObjectRecordEntry = 203,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_PROPERTY_INT")] AckPropertyInt = 210,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_PROPERTY_FLOAT")] AckPropertyFloat = 211,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_PROPERTY_STRING")] AckPropertyString = 212,
    /// <summary>
    ///EGMI_ACK_PROPERTY_DOUBLE					= 213;			//
    /// </summary>
    [pbr::OriginalName("ACK_PROPERTY_OBJECT")] AckPropertyObject = 214,
    [pbr::OriginalName("ACK_PROPERTY_VECTOR2")] AckPropertyVector2 = 215,
    [pbr::OriginalName("ACK_PROPERTY_VECTOR3")] AckPropertyVector3 = 216,
    [pbr::OriginalName("ACK_PROPERTY_CLEAR")] AckPropertyClear = 217,
    [pbr::OriginalName("ACK_ADD_ROW")] AckAddRow = 220,
    [pbr::OriginalName("ACK_REMOVE_ROW")] AckRemoveRow = 221,
    [pbr::OriginalName("ACK_SWAP_ROW")] AckSwapRow = 222,
    [pbr::OriginalName("ACK_RECORD_INT")] AckRecordInt = 223,
    [pbr::OriginalName("ACK_RECORD_FLOAT")] AckRecordFloat = 224,
    /// <summary>
    ///EGMI_ACK_RECORD_DOUBLE					= 225;
    /// </summary>
    [pbr::OriginalName("ACK_RECORD_STRING")] AckRecordString = 226,
    [pbr::OriginalName("ACK_RECORD_OBJECT")] AckRecordObject = 227,
    [pbr::OriginalName("ACK_RECORD_VECTOR2")] AckRecordVector2 = 228,
    [pbr::OriginalName("ACK_RECORD_VECTOR3")] AckRecordVector3 = 229,
    [pbr::OriginalName("ACK_RECORD_CLEAR")] AckRecordClear = 250,
    [pbr::OriginalName("ACK_RECORD_SORT")] AckRecordSort = 251,
    [pbr::OriginalName("ACK_DATA_FINISHED")] AckDataFinished = 260,
    [pbr::OriginalName("REQ_AI_ONWER")] ReqAiOnwer = 270,
    [pbr::OriginalName("REQ_MOVE")] ReqMove = 300,
    [pbr::OriginalName("ACK_MOVE")] AckMove = 301,
    [pbr::OriginalName("REQ_MOVE_IMMUNE")] ReqMoveImmune = 302,
    [pbr::OriginalName("ACK_MOVE_IMMUNE")] AckMoveImmune = 303,
    [pbr::OriginalName("REQ_POS_SYNC")] ReqPosSync = 306,
    [pbr::OriginalName("ACK_POS_SYNC")] AckPosSync = 307,
    [pbr::OriginalName("REQ_CHAT")] ReqChat = 350,
    [pbr::OriginalName("ACK_CHAT")] AckChat = 351,
    [pbr::OriginalName("REQ_SKILL_OBJECTX")] ReqSkillObjectx = 400,
    [pbr::OriginalName("ACK_SKILL_OBJECTX")] AckSkillObjectx = 401,
    [pbr::OriginalName("REQ_SKILL_POS")] ReqSkillPos = 402,
    [pbr::OriginalName("ACK_SKILL_POS")] AckSkillPos = 403,
    [pbr::OriginalName("ACK_ONLINE_NOTIFY")] AckOnlineNotify = 600,
    [pbr::OriginalName("ACK_OFFLINE_NOTIFY")] AckOfflineNotify = 601,
  }

  public enum EItemType {
    /// <summary>
    ///the equipment which can add props
    /// </summary>
    [pbr::OriginalName("EIT_EQUIP")] EitEquip = 0,
    /// <summary>
    ///the gem ca be embed to the equipment
    /// </summary>
    [pbr::OriginalName("EIT_GEM")] EitGem = 1,
    /// <summary>
    ///expendable items for player, such as a medicine that cures
    /// </summary>
    [pbr::OriginalName("EIT_SUPPLY")] EitSupply = 2,
    /// <summary>
    ///special items that can call a hero or others, special items can do what you want to do
    /// </summary>
    [pbr::OriginalName("EIT_SCROLL")] EitScroll = 3,
  }

  public enum ESkillType {
    /// <summary>
    ///this kind of skill just can damage one object
    /// </summary>
    [pbr::OriginalName("BRIEF_SINGLE_SKILL")] BriefSingleSkill = 0,
    /// <summary>
    ///this kind of skill can damage multiple objects
    /// </summary>
    [pbr::OriginalName("BRIEF_GROUP_SKILL")] BriefGroupSkill = 1,
    /// <summary>
    ///this kind of bullet just can damage one object
    /// </summary>
    [pbr::OriginalName("BULLET_SINGLE_SKILL")] BulletSingleSkill = 2,
    /// <summary>
    ///this kind of bullet can damage multiple objects via rebound
    /// </summary>
    [pbr::OriginalName("BULLET_REBOUND_SKILL")] BulletReboundSkill = 3,
    /// <summary>
    ///this kind of bullet can damage multiple objects who around the target when the bullet touched the target object
    /// </summary>
    [pbr::OriginalName("BULLET_TARGET_BOMB_SKILL")] BulletTargetBombSkill = 4,
    /// <summary>
    ///this kind of bullet can damage multiple objects  who around the target when the bullet arrived the position
    /// </summary>
    [pbr::OriginalName("BULLET_POS_BOMB_SKILL")] BulletPosBombSkill = 5,
    [pbr::OriginalName("FUNC_SKILL")] FuncSkill = 6,
  }

  public enum ESceneType {
    /// <summary>
    ///public town
    /// </summary>
    [pbr::OriginalName("NORMAL_SCENE")] NormalScene = 0,
    /// <summary>
    ///single boss underground city
    /// </summary>
    [pbr::OriginalName("SINGLE_CLONE_SCENE")] SingleCloneScene = 1,
    /// <summary>
    ///world boss underground city
    /// </summary>
    [pbr::OriginalName("MULTI_CLONE_SCENE")] MultiCloneScene = 2,
    [pbr::OriginalName("PVP_MODE_SCENE")] PvpModeScene = 10,
    [pbr::OriginalName("MVM_MODE_SCENE")] MvmModeScene = 11,
    [pbr::OriginalName("SURVIVAL_MODE_SCENE")] SurvivalModeScene = 12,
  }

  public enum ENPCType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("NORMAL_NPC")] NormalNpc = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("HERO_NPC")] HeroNpc = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TURRET_NPC")] TurretNpc = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("FUNC_NPC")] FuncNpc = 3,
  }

  #endregion

}

#endregion Designer generated code
