// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: NFDefine.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NFMsg {

  /// <summary>Holder for reflection information generated from NFDefine.proto</summary>
  public static partial class NFDefineReflection {

    #region Descriptor
    /// <summary>File descriptor for NFDefine.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NFDefineReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5ORkRlZmluZS5wcm90bxIFTkZNc2cqswMKDkVHYW1lRXZlbnRDb2RlEgsK",
            "B1NVQ0NFU1MQABIQCgxVTktPV05fRVJST1IQARIRCg1BQ0NPVU5UX0VYSVNU",
            "EAISFgoSQUNDT1VOVFBXRF9JTlZBTElEEAMSEQoNQUNDT1VOVF9VU0lORxAE",
            "EhIKDkFDQ09VTlRfTE9DS0VEEAUSEwoPQUNDT1VOVF9TVUNDRVNTEAYSFgoS",
            "VkVSSUZZX0tFWV9TVUNDRVNTEAcSEwoPVkVSSUZZX0tFWV9GQUlMEAgSGAoU",
            "U0VMRUNUU0VSVkVSX1NVQ0NFU1MQCRIVChFTRUxFQ1RTRVJWRVJfRkFJTBAK",
            "EhMKD0NIQVJBQ1RFUl9FWElTVBBuEhUKEVNWUlpPTkVJRF9JTlZBTElEEG8S",
            "FAoQQ0hBUkFDVEVSX05VTU9VVBBwEhUKEUNIQVJBQ1RFUl9JTlZBTElEEHES",
            "FgoSQ0hBUkFDVEVSX05PVEVYSVNUEHISEwoPQ0hBUkFDVEVSX1VTSU5HEHMS",
            "FAoQQ0hBUkFDVEVSX0xPQ0tFRBB0EhEKDVpPTkVfT1ZFUkxPQUQQdRIOCgpO",
            "T1RfT05MSU5FEHYqiREKCkVHYW1lTXNnSUQSCgoGVU5LTk9XEAASEAoMRVZF",
            "TlRfUkVTVUxUEAESEwoPRVZFTlRfVFJBTlNQT1JUEAISEAoMQ0xPU0VfU09D",
            "S0VUEAMSEwoPRVZFTlRfQlVZX0xFVkVMEAQSFgoSRVZFTlRfUkVGUkVTSF9T",
            "SE9QEAUSDgoKRVZFTlRfRVhJVBAGEhMKD0VWRU5UX1JFQ09OTkVDVBAHEhYK",
            "EkVWRU5UX0JVWV9DSEFNUElPThAIEhcKE0VWRU5UX1NFTExfQ0hBTVBJT04Q",
            "CRIYChRXVE1fV09STERfUkVHSVNURVJFRBAKEhoKFldUTV9XT1JMRF9VTlJF",
            "R0lTVEVSRUQQCxIVChFXVE1fV09STERfUkVGUkVTSBAMEhsKF0FDS19FVkVO",
            "VF9TRUxMX0NIQU1QSU9OEA0SGAoUTFRNX0xPR0lOX1JFR0lTVEVSRUQQFBIa",
            "ChZMVE1fTE9HSU5fVU5SRUdJU1RFUkVEEBUSFQoRTFRNX0xPR0lOX1JFRlJF",
            "U0gQFhIZChVQVFdHX1BST1hZX1JFR0lTVEVSRUQQHhIbChdQVFdHX1BST1hZ",
            "X1VOUkVHSVNURVJFRBAfEhYKElBUV0dfUFJPWFlfUkVGUkVTSBAgEhcKE0dU",
            "V19HQU1FX1JFR0lTVEVSRUQQKBIZChVHVFdfR0FNRV9VTlJFR0lTVEVSRUQQ",
            "KRIUChBHVFdfR0FNRV9SRUZSRVNIECoSFQoRRFRXX0RCX1JFR0lTVEVSRUQQ",
            "PBIXChNEVFdfREJfVU5SRUdJU1RFUkVEED0SEgoORFRXX0RCX1JFRlJFU0gQ",
            "PhIQCgxTVFNfTkVUX0lORk8QRhIQCgxSRVFfTEFHX1RFU1QQUBIVChFBQ0tf",
            "R0FURV9MQUdfVEVTVBBREhUKEUFDS19HQU1FX0xBR19URVNUEFISFQoRU1RT",
            "X1NFUlZFUl9SRVBPUlQQWhISCg5TVFNfSEVBUlRfQkVBVBBkEg0KCVJFUV9M",
            "T0dJThBlEg0KCUFDS19MT0dJThBmEg4KClJFUV9MT0dPVVQQZxISCg5SRVFf",
            "V09STERfTElTVBBuEhIKDkFDS19XT1JMRF9MSVNUEG8SFQoRUkVRX0NPTk5F",
            "Q1RfV09STEQQcBIVChFBQ0tfQ09OTkVDVF9XT1JMRBBxEhkKFVJFUV9LSUNL",
            "RURfRlJPTV9XT1JMRBByEhMKD1JFUV9DT05ORUNUX0tFWRB4EhMKD0FDS19D",
            "T05ORUNUX0tFWRB6EhYKEVJFUV9TRUxFQ1RfU0VSVkVSEIIBEhYKEUFDS19T",
            "RUxFQ1RfU0VSVkVSEIMBEhIKDVJFUV9ST0xFX0xJU1QQhAESEgoNQUNLX1JP",
            "TEVfTElTVBCFARIUCg9SRVFfQ1JFQVRFX1JPTEUQhgESFAoPUkVRX0RFTEVU",
            "RV9ST0xFEIcBEhUKEFJFUV9SRUNPVkVSX1JPTEUQiAESFwoSUkVRX0xPQURf",
            "Uk9MRV9EQVRBEIwBEhcKEkFDS19MT0FEX1JPTEVfREFUQRCNARIXChJSRVFf",
            "U0FWRV9ST0xFX0RBVEEQjgESFwoSQUNLX1NBVkVfUk9MRV9EQVRBEI8BEhMK",
            "DlJFUV9FTlRFUl9HQU1FEJYBEhMKDkFDS19FTlRFUl9HQU1FEJcBEhMKDlJF",
            "UV9MRUFWRV9HQU1FEJgBEhMKDkFDS19MRUFWRV9HQU1FEJkBEhMKDlJFUV9T",
            "V0FQX1NDRU5FEJsBEhMKDkFDS19TV0FQX1NDRU5FEJwBEhgKE1JFUV9TV0FQ",
            "X0hPTUVfU0NFTkUQnQESGAoTQUNLX1NXQVBfSE9NRV9TQ0VORRCeARIaChVS",
            "RVFfRU5URVJfR0FNRV9GSU5JU0gQnwESGgoVQUNLX0VOVEVSX0dBTUVfRklO",
            "SVNIEKABEhUKEEFDS19PQkpFQ1RfRU5UUlkQyAESFQoQQUNLX09CSkVDVF9M",
            "RUFWRRDJARIeChlBQ0tfT0JKRUNUX1BST1BFUlRZX0VOVFJZEMoBEhwKF0FD",
            "S19PQkpFQ1RfUkVDT1JEX0VOVFJZEMsBEhUKEEFDS19QUk9QRVJUWV9JTlQQ",
            "0gESFwoSQUNLX1BST1BFUlRZX0ZMT0FUENMBEhgKE0FDS19QUk9QRVJUWV9T",
            "VFJJTkcQ1AESGAoTQUNLX1BST1BFUlRZX09CSkVDVBDWARIZChRBQ0tfUFJP",
            "UEVSVFlfVkVDVE9SMhDXARIZChRBQ0tfUFJPUEVSVFlfVkVDVE9SMxDYARIX",
            "ChJBQ0tfUFJPUEVSVFlfQ0xFQVIQ2QESEAoLQUNLX0FERF9ST1cQ3AESEwoO",
            "QUNLX1JFTU9WRV9ST1cQ3QESEQoMQUNLX1NXQVBfUk9XEN4BEhMKDkFDS19S",
            "RUNPUkRfSU5UEN8BEhUKEEFDS19SRUNPUkRfRkxPQVQQ4AESFgoRQUNLX1JF",
            "Q09SRF9TVFJJTkcQ4gESFgoRQUNLX1JFQ09SRF9PQkpFQ1QQ4wESFwoSQUNL",
            "X1JFQ09SRF9WRUNUT1IyEOQBEhcKEkFDS19SRUNPUkRfVkVDVE9SMxDlARIV",
            "ChBBQ0tfUkVDT1JEX0NMRUFSEPoBEhQKD0FDS19SRUNPUkRfU09SVBD7ARIW",
            "ChFBQ0tfREFUQV9GSU5JU0hFRBCEAhINCghSRVFfTU9WRRCsAhINCghBQ0tf",
            "TU9WRRCtAhINCghSRVFfQ0hBVBDeAhINCghBQ0tfQ0hBVBDfAhIWChFSRVFf",
            "U0tJTExfT0JKRUNUWBCQAxIWChFBQ0tfU0tJTExfT0JKRUNUWBCRAxISCg1S",
            "RVFfU0tJTExfUE9TEJIDEhIKDUFDS19TS0lMTF9QT1MQkwMSFgoRQUNLX09O",
            "TElORV9OT1RJRlkQ2AQSFwoSQUNLX09GRkxJTkVfTk9USUZZENkEKkcKCUVJ",
            "dGVtVHlwZRINCglFSVRfRVFVSVAQABILCgdFSVRfR0VNEAESDgoKRUlUX1NV",
            "UFBMWRACEg4KCkVJVF9TQ1JPTEwQAyq3AQoKRVNraWxsVHlwZRIWChJCUklF",
            "Rl9TSU5HTEVfU0tJTEwQABIVChFCUklFRl9HUk9VUF9TS0lMTBABEhcKE0JV",
            "TExFVF9TSU5HTEVfU0tJTEwQAhIYChRCVUxMRVRfUkVCT1VORF9TS0lMTBAD",
            "EhwKGEJVTExFVF9UQVJHRVRfQk9NQl9TS0lMTBAEEhkKFUJVTExFVF9QT1Nf",
            "Qk9NQl9TS0lMTBAFEg4KCkZVTkNfU0tJTEwQBipNCgpFU2NlbmVUeXBlEhAK",
            "DE5PUk1BTF9TQ0VORRAAEhYKElNJTkdMRV9DTE9ORV9TQ0VORRABEhUKEU1V",
            "TFRJX0NMT05FX1NDRU5FEAIqRgoIRU5QQ1R5cGUSDgoKTk9STUFMX05QQxAA",
            "EgwKCEhFUk9fTlBDEAESDgoKVFVSUkVUX05QQxACEgwKCEZVTkNfTlBDEANi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::NFMsg.EGameEventCode), typeof(global::NFMsg.EGameMsgID), typeof(global::NFMsg.EItemType), typeof(global::NFMsg.ESkillType), typeof(global::NFMsg.ESceneType), typeof(global::NFMsg.ENPCType), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///events
  /// </summary>
  public enum EGameEventCode {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("SUCCESS")] Success = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("UNKOWN_ERROR")] UnkownError = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACCOUNT_EXIST")] AccountExist = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACCOUNTPWD_INVALID")] AccountpwdInvalid = 3,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACCOUNT_USING")] AccountUsing = 4,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACCOUNT_LOCKED")] AccountLocked = 5,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACCOUNT_SUCCESS")] AccountSuccess = 6,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("VERIFY_KEY_SUCCESS")] VerifyKeySuccess = 7,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("VERIFY_KEY_FAIL")] VerifyKeyFail = 8,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("SELECTSERVER_SUCCESS")] SelectserverSuccess = 9,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("SELECTSERVER_FAIL")] SelectserverFail = 10,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("CHARACTER_EXIST")] CharacterExist = 110,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("SVRZONEID_INVALID")] SvrzoneidInvalid = 111,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("CHARACTER_NUMOUT")] CharacterNumout = 112,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("CHARACTER_INVALID")] CharacterInvalid = 113,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("CHARACTER_NOTEXIST")] CharacterNotexist = 114,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("CHARACTER_USING")] CharacterUsing = 115,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("CHARACTER_LOCKED")] CharacterLocked = 116,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ZONE_OVERLOAD")] ZoneOverload = 117,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("NOT_ONLINE")] NotOnline = 118,
  }

  public enum EGameMsgID {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("UNKNOW")] Unknow = 0,
    /// <summary>
    /// for events
    /// </summary>
    [pbr::OriginalName("EVENT_RESULT")] EventResult = 1,
    /// <summary>
    /// for events
    /// </summary>
    [pbr::OriginalName("EVENT_TRANSPORT")] EventTransport = 2,
    /// <summary>
    /// want to close some one
    /// </summary>
    [pbr::OriginalName("CLOSE_SOCKET")] CloseSocket = 3,
    [pbr::OriginalName("EVENT_BUY_LEVEL")] EventBuyLevel = 4,
    [pbr::OriginalName("EVENT_REFRESH_SHOP")] EventRefreshShop = 5,
    [pbr::OriginalName("EVENT_EXIT")] EventExit = 6,
    [pbr::OriginalName("EVENT_RECONNECT")] EventReconnect = 7,
    [pbr::OriginalName("EVENT_BUY_CHAMPION")] EventBuyChampion = 8,
    [pbr::OriginalName("EVENT_SELL_CHAMPION")] EventSellChampion = 9,
    [pbr::OriginalName("WTM_WORLD_REGISTERED")] WtmWorldRegistered = 10,
    [pbr::OriginalName("WTM_WORLD_UNREGISTERED")] WtmWorldUnregistered = 11,
    [pbr::OriginalName("WTM_WORLD_REFRESH")] WtmWorldRefresh = 12,
    [pbr::OriginalName("ACK_EVENT_SELL_CHAMPION")] AckEventSellChampion = 13,
    [pbr::OriginalName("LTM_LOGIN_REGISTERED")] LtmLoginRegistered = 20,
    [pbr::OriginalName("LTM_LOGIN_UNREGISTERED")] LtmLoginUnregistered = 21,
    [pbr::OriginalName("LTM_LOGIN_REFRESH")] LtmLoginRefresh = 22,
    [pbr::OriginalName("PTWG_PROXY_REGISTERED")] PtwgProxyRegistered = 30,
    [pbr::OriginalName("PTWG_PROXY_UNREGISTERED")] PtwgProxyUnregistered = 31,
    [pbr::OriginalName("PTWG_PROXY_REFRESH")] PtwgProxyRefresh = 32,
    [pbr::OriginalName("GTW_GAME_REGISTERED")] GtwGameRegistered = 40,
    [pbr::OriginalName("GTW_GAME_UNREGISTERED")] GtwGameUnregistered = 41,
    [pbr::OriginalName("GTW_GAME_REFRESH")] GtwGameRefresh = 42,
    [pbr::OriginalName("DTW_DB_REGISTERED")] DtwDbRegistered = 60,
    [pbr::OriginalName("DTW_DB_UNREGISTERED")] DtwDbUnregistered = 61,
    [pbr::OriginalName("DTW_DB_REFRESH")] DtwDbRefresh = 62,
    [pbr::OriginalName("STS_NET_INFO")] StsNetInfo = 70,
    [pbr::OriginalName("REQ_LAG_TEST")] ReqLagTest = 80,
    [pbr::OriginalName("ACK_GATE_LAG_TEST")] AckGateLagTest = 81,
    [pbr::OriginalName("ACK_GAME_LAG_TEST")] AckGameLagTest = 82,
    [pbr::OriginalName("STS_SERVER_REPORT")] StsServerReport = 90,
    [pbr::OriginalName("STS_HEART_BEAT")] StsHeartBeat = 100,
    /// <summary>
    ///////////////////////////////////////////////////////////////////////////////////////
    /// </summary>
    [pbr::OriginalName("REQ_LOGIN")] ReqLogin = 101,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_LOGIN")] AckLogin = 102,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_LOGOUT")] ReqLogout = 103,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_WORLD_LIST")] ReqWorldList = 110,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_WORLD_LIST")] AckWorldList = 111,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_CONNECT_WORLD")] ReqConnectWorld = 112,
    [pbr::OriginalName("ACK_CONNECT_WORLD")] AckConnectWorld = 113,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_KICKED_FROM_WORLD")] ReqKickedFromWorld = 114,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_CONNECT_KEY")] ReqConnectKey = 120,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_CONNECT_KEY")] AckConnectKey = 122,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_SELECT_SERVER")] ReqSelectServer = 130,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_SELECT_SERVER")] AckSelectServer = 131,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_ROLE_LIST")] ReqRoleList = 132,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_ROLE_LIST")] AckRoleList = 133,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_CREATE_ROLE")] ReqCreateRole = 134,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_DELETE_ROLE")] ReqDeleteRole = 135,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_RECOVER_ROLE")] ReqRecoverRole = 136,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_LOAD_ROLE_DATA")] ReqLoadRoleData = 140,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_LOAD_ROLE_DATA")] AckLoadRoleData = 141,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_SAVE_ROLE_DATA")] ReqSaveRoleData = 142,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_SAVE_ROLE_DATA")] AckSaveRoleData = 143,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_ENTER_GAME")] ReqEnterGame = 150,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_ENTER_GAME")] AckEnterGame = 151,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_LEAVE_GAME")] ReqLeaveGame = 152,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_LEAVE_GAME")] AckLeaveGame = 153,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_SWAP_SCENE")] ReqSwapScene = 155,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_SWAP_SCENE")] AckSwapScene = 156,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_SWAP_HOME_SCENE")] ReqSwapHomeScene = 157,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_SWAP_HOME_SCENE")] AckSwapHomeScene = 158,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("REQ_ENTER_GAME_FINISH")] ReqEnterGameFinish = 159,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_ENTER_GAME_FINISH")] AckEnterGameFinish = 160,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_OBJECT_ENTRY")] AckObjectEntry = 200,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_OBJECT_LEAVE")] AckObjectLeave = 201,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_OBJECT_PROPERTY_ENTRY")] AckObjectPropertyEntry = 202,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_OBJECT_RECORD_ENTRY")] AckObjectRecordEntry = 203,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_PROPERTY_INT")] AckPropertyInt = 210,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_PROPERTY_FLOAT")] AckPropertyFloat = 211,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_PROPERTY_STRING")] AckPropertyString = 212,
    /// <summary>
    ///EGMI_ACK_PROPERTY_DOUBLE				= 213;			//
    /// </summary>
    [pbr::OriginalName("ACK_PROPERTY_OBJECT")] AckPropertyObject = 214,
    [pbr::OriginalName("ACK_PROPERTY_VECTOR2")] AckPropertyVector2 = 215,
    [pbr::OriginalName("ACK_PROPERTY_VECTOR3")] AckPropertyVector3 = 216,
    [pbr::OriginalName("ACK_PROPERTY_CLEAR")] AckPropertyClear = 217,
    [pbr::OriginalName("ACK_ADD_ROW")] AckAddRow = 220,
    [pbr::OriginalName("ACK_REMOVE_ROW")] AckRemoveRow = 221,
    [pbr::OriginalName("ACK_SWAP_ROW")] AckSwapRow = 222,
    [pbr::OriginalName("ACK_RECORD_INT")] AckRecordInt = 223,
    [pbr::OriginalName("ACK_RECORD_FLOAT")] AckRecordFloat = 224,
    /// <summary>
    ///EGMI_ACK_RECORD_DOUBLE				= 225;
    /// </summary>
    [pbr::OriginalName("ACK_RECORD_STRING")] AckRecordString = 226,
    [pbr::OriginalName("ACK_RECORD_OBJECT")] AckRecordObject = 227,
    [pbr::OriginalName("ACK_RECORD_VECTOR2")] AckRecordVector2 = 228,
    [pbr::OriginalName("ACK_RECORD_VECTOR3")] AckRecordVector3 = 229,
    [pbr::OriginalName("ACK_RECORD_CLEAR")] AckRecordClear = 250,
    [pbr::OriginalName("ACK_RECORD_SORT")] AckRecordSort = 251,
    [pbr::OriginalName("ACK_DATA_FINISHED")] AckDataFinished = 260,
    [pbr::OriginalName("REQ_MOVE")] ReqMove = 300,
    [pbr::OriginalName("ACK_MOVE")] AckMove = 301,
    [pbr::OriginalName("REQ_CHAT")] ReqChat = 350,
    [pbr::OriginalName("ACK_CHAT")] AckChat = 351,
    [pbr::OriginalName("REQ_SKILL_OBJECTX")] ReqSkillObjectx = 400,
    [pbr::OriginalName("ACK_SKILL_OBJECTX")] AckSkillObjectx = 401,
    [pbr::OriginalName("REQ_SKILL_POS")] ReqSkillPos = 402,
    [pbr::OriginalName("ACK_SKILL_POS")] AckSkillPos = 403,
    [pbr::OriginalName("ACK_ONLINE_NOTIFY")] AckOnlineNotify = 600,
    [pbr::OriginalName("ACK_OFFLINE_NOTIFY")] AckOfflineNotify = 601,
  }

  public enum EItemType {
    /// <summary>
    ///the equipment which can add props
    /// </summary>
    [pbr::OriginalName("EIT_EQUIP")] EitEquip = 0,
    /// <summary>
    ///the gem ca be embed to the equipment
    /// </summary>
    [pbr::OriginalName("EIT_GEM")] EitGem = 1,
    /// <summary>
    ///expendable items for player, such as a medicine that cures
    /// </summary>
    [pbr::OriginalName("EIT_SUPPLY")] EitSupply = 2,
    /// <summary>
    ///special items that can call a hero or others, special items can do what you want to do
    /// </summary>
    [pbr::OriginalName("EIT_SCROLL")] EitScroll = 3,
  }

  public enum ESkillType {
    /// <summary>
    ///this kind of skill just can damage one object
    /// </summary>
    [pbr::OriginalName("BRIEF_SINGLE_SKILL")] BriefSingleSkill = 0,
    /// <summary>
    ///this kind of skill can damage multiple objects
    /// </summary>
    [pbr::OriginalName("BRIEF_GROUP_SKILL")] BriefGroupSkill = 1,
    /// <summary>
    ///this kind of bullet just can damage one object
    /// </summary>
    [pbr::OriginalName("BULLET_SINGLE_SKILL")] BulletSingleSkill = 2,
    /// <summary>
    ///this kind of bullet can damage multiple objects via rebound
    /// </summary>
    [pbr::OriginalName("BULLET_REBOUND_SKILL")] BulletReboundSkill = 3,
    /// <summary>
    ///this kind of bullet can damage multiple objects who around the target when the bullet touched the target object
    /// </summary>
    [pbr::OriginalName("BULLET_TARGET_BOMB_SKILL")] BulletTargetBombSkill = 4,
    /// <summary>
    ///this kind of bullet can damage multiple objects  who around the target when the bullet arrived the position
    /// </summary>
    [pbr::OriginalName("BULLET_POS_BOMB_SKILL")] BulletPosBombSkill = 5,
    [pbr::OriginalName("FUNC_SKILL")] FuncSkill = 6,
  }

  public enum ESceneType {
    /// <summary>
    ///public town, only has one group available for players is 1
    /// </summary>
    [pbr::OriginalName("NORMAL_SCENE")] NormalScene = 0,
    /// <summary>
    ///private room, only has one player per group and it will be destroyed if the player leaved from group.
    /// </summary>
    [pbr::OriginalName("SINGLE_CLONE_SCENE")] SingleCloneScene = 1,
    /// <summary>
    ///private room, only has more than one player per group and it will be destroyed if all players leaved from group.
    /// </summary>
    [pbr::OriginalName("MULTI_CLONE_SCENE")] MultiCloneScene = 2,
  }

  public enum ENPCType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("NORMAL_NPC")] NormalNpc = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("HERO_NPC")] HeroNpc = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TURRET_NPC")] TurretNpc = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("FUNC_NPC")] FuncNpc = 3,
  }

  #endregion

}

#endregion Designer generated code
